---
- name: Deploy Monitoring Stack
  hosts: "{{ target_hosts | default('single_node') }}"
  become: true
  
  vars:
    deployment_type: "{{ deploy_type | default('single') }}"
    deploy_components:
      grafana: false
      node_exporter: false
      process_exporter: false
      prometheus: false

  pre_tasks:
    - name: Validate system requirements
      ansible.builtin.assert:
        that:
          - ansible_distribution in ['Ubuntu', 'Debian', 'CentOS', 'RedHat', 'Fedora']
          - ansible_distribution_major_version is version('18', '>=')
        msg: "This playbook requires a supported Linux distribution"
        
  tasks:
    - name: Deploy Grafana
      include_role:
        name: grafana
      when: >
        deploy_components.grafana | bool and
        (deployment_type == 'single' or inventory_hostname in groups['grafana'])
      tags: ['grafana']

    - name: Deploy Node Exporter
      include_role:
        name: node_exporter
      when: >
        deploy_components.node_exporter | bool and
        (deployment_type == 'single' or inventory_hostname in groups['node_exporter'])
      tags: ['node_exporter']

    - name: Deploy Process Exporter
      include_tasks: roles/process_exporter/playbook.yml
      when: >
        deploy_components.process_exporter | bool and
        (deployment_type == 'single' or inventory_hostname in groups['process_exporter'])
      tags: ['process_exporter']

    - name: Deploy Prometheus
      include_role:
        name: prometheus
      when: >
        deploy_components.prometheus | bool and
        (deployment_type == 'single' or inventory_hostname in groups['prometheus'])
      tags: ['prometheus']