---
# Download Process Exporter
- name: Download Process Exporter tarball
  get_url:
    url: "https://github.com/ncabatoff/process-exporter/releases/download/v0.7.10/process-exporter-0.7.10.linux-amd64.tar.gz"
    dest: "/tmp/process-exporter.tar.gz"

# Extract Process Exporter
- name: Extract Process Exporter
  unarchive:
    src: "/tmp/process-exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes

# Move binary to /usr/local/bin
- name: Move Process Exporter binary to /usr/local/bin
  command: mv /tmp/process-exporter-0.7.10.linux-amd64/process-exporter /usr/local/bin/

# Create configuration directory
- name: Create configuration directory for Process Exporter
  file:
    path: "/usr/bin/process-exporter"
    state: directory
    mode: '0755'

# Create configuration file
- name: Create Process Exporter configuration file
  copy:
    dest: "/usr/bin/process-exporter/config.yml"
    content: |
      process_names:
        - name: "nginx"
          cmdline:
            - "nginx"
        - name: "ssh"
          cmdline:
            - "sshd"

# Create systemd service file
- name: Create Process Exporter systemd service
  template:
    src: process-exporter.service.j2
    dest: "/etc/systemd/system/process-exporter.service"
    mode: '0644'

# Reload systemd daemon
- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

# Start Process Exporter service
- name: Start Process Exporter service
  systemd:
    name: process-exporter
    state: started
    enabled: true

# Wait for service to be ready
- name: Wait for Process Exporter to be ready
  wait_for:
    port: 9256
    timeout: 30
  register: wait_result
  ignore_errors: yes

# Verify Process Exporter service status
- name: Check Process Exporter service status
  command: systemctl status process-exporter
  register: status_output
  failed_when: status_output.rc != 0
  changed_when: false
  ignore_errors: yes

# Display service status
- name: Show service status
  debug:
    msg: "ok: [{{ inventory_hostname }}]"
  when: status_output is defined

# Test Process Exporter endpoint
- name: Test Process Exporter metrics endpoint
  uri:
    url: "http://localhost:9256/metrics"
    status_code: 200
    validate_certs: no
    timeout: 5
  register: metrics_check
  until: metrics_check.status == 200
  retries: 6
  delay: 5
  ignore_errors: yes
